// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// import 'firebase_options.dart';
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL7rNvG3EnpSc46mAz0w77YJbtHUO4JUs',
    appId: '1:1094777996506:android:7d84cc005f4a038f3191e3',
    messagingSenderId: '1094777996506',
    projectId: 'roadsense-3e4b2',
    storageBucket: 'roadsense-3e4b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4REltgkaUhhebReZvpFvThMslDgJs9mM',
    appId: '1:1094777996506:ios:4f1f53141f9d62ec3191e3',
    messagingSenderId: '1094777996506',
    projectId: 'roadsense-3e4b2',
    storageBucket: 'roadsense-3e4b2.firebasestorage.app',
    iosBundleId: 'com.example.roadsense',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZvUFWvlpfJOP7czL4HCpL9TbASCTcZQ',
    appId: '1:1094777996506:web:500e3603517a9e353191e3',
    messagingSenderId: '1094777996506',
    projectId: 'roadsense-3e4b2',
    authDomain: 'roadsense-3e4b2.firebaseapp.com',
    storageBucket: 'roadsense-3e4b2.firebasestorage.app',
    measurementId: 'G-T7F9M7LHT1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4REltgkaUhhebReZvpFvThMslDgJs9mM',
    appId: '1:1094777996506:ios:4f1f53141f9d62ec3191e3',
    messagingSenderId: '1094777996506',
    projectId: 'roadsense-3e4b2',
    storageBucket: 'roadsense-3e4b2.firebasestorage.app',
    iosBundleId: 'com.example.roadsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrZvUFWvlpfJOP7czL4HCpL9TbASCTcZQ',
    appId: '1:1094777996506:web:21b5089d9ef47de33191e3',
    messagingSenderId: '1094777996506',
    projectId: 'roadsense-3e4b2',
    authDomain: 'roadsense-3e4b2.firebaseapp.com',
    storageBucket: 'roadsense-3e4b2.firebasestorage.app',
    measurementId: 'G-J51JP0K97H',
  );

}